resources:
  - name: myFirstRepo1
    type: GitRepo
    configuration:
      gitProvider: mygithub
      path: kunal-mazumdar/pipelines-local-test-repo
      
  - name: myPropertyBagx
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
      
  - name: myPropertyBagx2
    type: PropertyBag
    configuration:
      commitSha: 2
      runID: 2

pipelines:
  - name: demo_manual
    configuration:
      inputResources:
        - name: myFirstRepo1
    steps:
      - name: manual_trigger
        type: Bash
        configuration:
          inputResources:
            - name: myPropertyBagx
        execution:
          onExecute:
            - printenv
            - echo "hi"
